### PR TITLE
big database update

### PR DESCRIPTION
**Pull request by TWolczanski**
I updated the REPLACEMENTS list from data.py by ~3500 LaTeX commands. I also fixed \mathcal{o} and \mathcal{O}.

### CODE REVIEW

**Comment by svenkreiss** [comment]
Thanks! 

Can you change the indentation to four whitespaces and add a note linking the license in the LICENSE file?

**Comment by TWolczanski** [comment]
I've changed the indentation.

> add a note linking the license in the LICENSE file
What do you mean by that?

**Comment by svenkreiss** [comment]
Thanks.

The file where you took the symbols from has a license. I think that license needs to be acknowledged in unicodeit's license file with this PR.

**Comment by TWolczanski** [comment]
I added the whole LPPL 1.3c to the LICENSE file but possibly I should have included only lines 363-379 (properly modified). What do you think?

**Comment by svenkreiss** [comment]
Thanks @TWolczanski .
I am not an expert on licensing, but the way I understand it, the whole license must be included. Can you create a separate file `LICENSE.LPPL` and put this text there? In our main `LICENSE` file, can you add this chunk at the bottom:

```
=====================

Some symbols were extracted from: http://milde.users.sourceforge.net/LUCR/Math/data/unimathsymbols.txt
which is Copyright 2011 by GÃ¼nter Milde and licensed under the LaTeX Project Public License (LPPL)
included here as LICENSE.LPPL.
```

**Comment by svenkreiss** [comment]
Thank you @TWolczanski ! Great contribution.

**Pull request merged**
