### PR TITLE
Added all the mathbb uppercases

### PR DESCRIPTION
**Pull request by Enevevet**
And removed the old "\mathbb{D}" wich was the unicode for **italic** double-struck D.

### CODE REVIEW

**Comment by svenkreiss** [comment]
Thank you @Enevevet . This looks good. Can you fix the test as well? Otherwise I can look into that.

In #31, we are moving to MIT License. Please give your short "okay" here in a comment to that licensing. Thanks.

**Comment by Enevevet** [comment]
> Thank you @Enevevet . This looks good. Can you fix the test as well? Otherwise I can look into that.
> 
> In #31, we are moving to MIT License. Please give your short "okay" here in a comment to that licensing. Thanks.

Okay for the License!

**Comment by Enevevet** [comment]
I can't get rid of the test errors though, sorry for that... Could you please look into that?

**Comment by svenkreiss** [comment]
Apologies for only getting back to this now. This is only a side project for me. Another much larger data update has landed meanwhile. Please have a look at 0.7.1.

**Pull request closed without merging**
