### PR TITLE
Update automator instructions

### PR DESCRIPTION
**Pull request by MilesCranmer**
It seems like the new way to add this to automator is with "Service" instead of "Workflow". The options don't show up for workflow.

### CODE REVIEW

**Comment by svenkreiss** [comment]
The dialog to create something new in Automator looks like this for me:
image

I selected `Quick Action`. I don't actually have the "Service" option. Are we looking at different dialogs?

**Comment by MilesCranmer** [comment]
Ah, it probably changes between macOS versions - we could say both names in the readme.

I'm on High Sierra 10.13.6. What's your version?

**Comment by MilesCranmer** [comment]
Yeah, mine is called "Service"
Screen Shot 2020-07-10 at 12 20 51 PM

**Comment by MilesCranmer** [comment]
Changed the readme to mention both variations - does that sound good?

**Comment by svenkreiss** [comment]
Strange that yours is different. Mac OS must have renamed it.

Thanks for the fast fix! This PR looks good to me.

... at some point we need a short screen cast.

**Comment by svenkreiss** [comment]
Indeed, I am on 10.15.

**Pull request merged**
