### PR TITLE
\not\in and \notin

### PR DESCRIPTION
**Pull request by davidweichiang**

### CODE REVIEW

**Comment by davidweichiang** [comment]
There are many symbols that can be created with \not (https://www.compart.com/en/unicode/U+0338), many of which are already in the data as \nexists, etc. Would it be good to add all of them, or perhaps there's a way to do it algorithmically?

**Comment by svenkreiss** [comment]
Hello @davidweichiang , thanks! Looks good to me. 

In #31 , we are adding the MIT License to this repository. Can you give your quick "okay" in a comment to that licensing? Thanks.

**Comment by davidweichiang** [comment]
of course, thanks!

do you think it’s desirable to handle all combinations of \not algoriithmically, e.g. by translating \not * into * U+0338?

**Comment by svenkreiss** [comment]
Honestly, I don't know. I am open to suggestions. The current parser is far from perfect. We do already have some "combining marks": https://github.com/svenkreiss/unicodeit/blob/36e26dd7c4026a9190c1089947ef3971353f4c69/unicodeit/data.py#L698

Is `\not` similar?

**Comment by davidweichiang** [comment]
Yes, I think it’d be the same.

**Pull request merged**
