### PR TITLE
MIT License

### PR DESCRIPTION
**Pull request by svenkreiss**
Hello @pseyfert @christianp @kmyk @MilesCranmer @mattleblanc @duetosymmetry ,
We are moving to MIT License. As contributors, you own the copyright to your contribution. Please give me a brief "okay" in the comments to show you agree with the licensing. Please get in touch if this is a problem for you.

### CODE REVIEW

**Comment by christianp** [comment]
I'm fine to move to MIT

**Comment by kmyk** [comment]
It's okay :smile:

**Comment by pseyfert** [comment]
okay

**Comment by duetosymmetry** [comment]
Okay by me

**Comment by MilesCranmer** [comment]
Okay with me

**Pull request merged**
